import React, { useState } from 'react';
import Modal from '../../components/Modal/Modal';
import './AdminPage.css';

const AdminPage = () => {
    const [isModalOpen, setIsModalOpen] = useState(false);
    const [modalContent, setModalContent] = useState({ title: '', content: '' });
    const [flightPassengers, setFlightPassengers] = useState(null); // Store passengers data
    const [flightDetails, setFlightDetails] = useState(null); // Store flight details data
    const [revenueData, setRevenueData] = useState(null); // Store revenue data

    const handleButtonClick = (title) => {
        setModalContent({ title, content: '' });
        setIsModalOpen(true);
    };

    const fetchPassengersByFlight = (flightId) => {
        // Simulating a backend API call that fetches passengers based on flight ID
        const passengers = [
            { id: 1, name: 'John Doe', age: 17, flightId: flightId },
            { id: 2, name: 'Jane Doe', age: 25, flightId: flightId },
            { id: 3, name: 'Alice Smith', age: 16, flightId: flightId },
            { id: 4, name: 'Bob Johnson', age: 30, flightId: flightId },
        ];
        const filteredPassengers = passengers.filter(p => p.flightId === flightId);
        return filteredPassengers;
    };

    const handleFlightIdSubmit = (flightId) => {
        console.log('Flight ID:', flightId);
        const passengers = fetchPassengersByFlight(flightId);

        // Separate passengers into below and above age 18
        const below18 = passengers.filter(p => p.age < 18);
        const above18 = passengers.filter(p => p.age >= 18);

        // Set the passengers data
        setFlightPassengers({ below18, above18 });
        setIsModalOpen(false);
    };

    const fetchFlightsByOriginAndDestination = ({ originId, destinationId }) => {
        // Simulating a backend API call that fetches flight details based on origin and destination
        const flights = [
            { flightId: 'FL001', origin: 'Airport A', destination: 'Airport B', passengersCount: 100 },
            { flightId: 'FL002', origin: 'Airport A', destination: 'Airport C', passengersCount: 150 },
            { flightId: 'FL003', origin: 'Airport B', destination: 'Airport A', passengersCount: 200 },
        ];

        const filteredFlights = flights.filter(flight => flight.origin === originId && flight.destination === destinationId);
        return filteredFlights;
    };

    const handleFlightDestinationSubmit = ({ originId, destinationId }) => {
        console.log('Origin ID:', originId, 'Destination ID:', destinationId);
        const flights = fetchFlightsByOriginAndDestination({ originId, destinationId });
        setFlightDetails(flights);
        setIsModalOpen(false);
    };

    const fetchTotalRevenueByAircraft = () => {
        // Simulating a backend API call that fetches revenue generated by each aircraft model
        const revenueData = [
            { model: 'Boeing 737', revenue: 500000 },
            { model: 'Airbus A320', revenue: 450000 },
            { model: 'Boeing 777', revenue: 700000 },
        ];
        return revenueData;
    };

    const handleTotalRevenueSubmit = () => {
        const revenueData = fetchTotalRevenueByAircraft();
        setRevenueData(revenueData);
        setIsModalOpen(false); // Close the modal
    };

    return (
        <div className='cont-body'>
            <div className="contain0">
                <h1>Admin Dashboard</h1>
                <div className="button-container">
                    <button onClick={() => handleButtonClick('Passengers by Flight')}>Passengers by Flight</button>
                    <button onClick={() => handleButtonClick('Passengers by Destination')}>Passengers by Destination</button>
                    <button onClick={() => handleButtonClick('Number of Bookings by Passenger')}>Number of Bookings by Passenger</button>
                    <button onClick={() => handleButtonClick('Flights by Destination and Origin')}>Flights by Destination and Origin</button>
                    <button onClick={() => handleButtonClick('Total Revenue by Aircraft')}>Total Revenue by Aircraft</button>
                </div>

                <Modal 
                    isOpen={isModalOpen} 
                    onClose={() => setIsModalOpen(false)} 
                    title={modalContent.title} 
                    onSubmit={
                        modalContent.title === 'Passengers by Flight' ? handleFlightIdSubmit :
                        modalContent.title === 'Flights by Destination and Origin' ? handleFlightDestinationSubmit :
                        modalContent.title === 'Total Revenue by Aircraft' ? handleTotalRevenueSubmit : 
                        null
                    }
                />

                {flightPassengers && (
                    <div className="passenger-tables">
                        <div>
                            <h2>Passengers Below Age 18</h2>
                            <table>
                                <thead>
                                    <tr>
                                        <th>Passenger ID</th>
                                        <th>Name</th>
                                        <th>Age</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {flightPassengers.below18.map((passenger) => (
                                        <tr key={passenger.id}>
                                            <td>{passenger.id}</td>
                                            <td>{passenger.name}</td>
                                            <td>{passenger.age}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>

                        <div>
                            <h2>Passengers Above Age 18</h2>
                            <table>
                                <thead>
                                    <tr>
                                        <th>Passenger ID</th>
                                        <th>Name</th>
                                        <th>Age</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {flightPassengers.above18.map((passenger) => (
                                        <tr key={passenger.id}>
                                            <td>{passenger.id}</td>
                                            <td>{passenger.name}</td>
                                            <td>{passenger.age}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    </div>
                )}

                {flightDetails && (
                    <div className="flight-details">
                        <h2>Flight Details</h2>
                        <table>
                            <thead>
                                <tr>
                                    <th>Flight ID</th>
                                    <th>Origin</th>
                                    <th>Destination</th>
                                    <th>Passengers Count</th>
                                </tr>
                            </thead>
                            <tbody>
                                {flightDetails.map((flight) => (
                                    <tr key={flight.flightId}>
                                        <td>{flight.flightId}</td>
                                        <td>{flight.origin}</td>
                                        <td>{flight.destination}</td>
                                        <td>{flight.passengersCount}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}

                {revenueData && (
                    <div className="revenue-data">
                        <h2>Total Revenue by Aircraft</h2>
                        <table>
                            <thead>
                                <tr>
                                    <th>Aircraft Model</th>
                                    <th>Total Revenue</th>
                                </tr>
                            </thead>
                            <tbody>
                                {revenueData.map((data) => (
                                    <tr key={data.model}>
                                        <td>{data.model}</td>
                                        <td>${data.revenue.toLocaleString()}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                )}
            </div>
        </div>
    );
};

export default AdminPage;
